comandos linux para iniciantes
PHPSP/phpsp.org.br pull request #497
Opened 2023-12-27 01:06 UTC by Elissdev

Neste artigo, escrevi sobre alguns comandos básicos para iniciantes, que me ajuda muito, e acredito que também será útil para quem está começando, assim como eu :)

2023-12-28 08:11 UTC, nawarian requested changes
Sensacional! Obrigado pelo artigo @Elissdev !

Vou te pedir uma pequena mudança pra organizar o texto melhor, só. A cada comando que tu explica usa um subtítulo através do `##` que vai ficar show!

2023-12-28 08:11 UTC, nawarian commented on source/_posts/comandos-linux-para-iniciantes.md
> +pwd (Print Working Directory): Usado para descobrir qual diretório atual está sendo utilizado ao acionar o comando, o terminal exibe o endereço completo do diretório começando pelo root.
Acho que ficaria melhor se tu transformasse isso em um subtitulo, por exemplo assim:

```
## Comando `pwd` - Print working directory

Usado para descobrir qual...
```

Esse `##` no começo da linha transforma a linha em subtítulo, e deixa o texto mais facinho de acompanahr :)

2024-01-01 22:24 UTC, Elissdev commented
Obrigada! Blz, @nawarian pode deixar :)

2024-01-03 12:21 UTC, nawarian requested changes

2024-01-03 12:21 UTC, nawarian commented on source/_posts/comandos-linux-para-iniciantes.md
> +touch texto1 texto2 texto3 texto4 texto5
Recomendo colocar os comandos entre crases, pra dar uma formatação especial.

Se você escrever \`touch texto1 texto2 texto3 texto4 texto5\` ele vai aparecer assim: `touch texto1 texto2 texto3 texto4 texto5`

Faz uma revisão no texto pra ajeitar isso e pra mim tá bom já, daí eu já faço o merge :heart:

2024-01-04 00:16 UTC, Elissdev commented on source/_posts/comandos-linux-para-iniciantes.md
> +touch texto1 texto2 texto3 texto4 texto5
Certo! Agora foi! Revisado e reajustado, se tiver algo a mais pra alterar pode mandar! ^^

2024-01-04 16:27 UTC, nawarian commented on source/_posts/comandos-linux-para-iniciantes.md
> +touch texto1 texto2 texto3 texto4 texto5
Acho que algumas partes ficaram estranhas, olha os prints:

Aqui o texto "-> para criar um arquivo ..." näo faz parte do comando

![image](https://github.com/PHPSP/phpsp.org.br/assets/3905582/0bd483aa-6cc9-42cd-b05d-91486e677850)

Aqui tem dois comandos `cd` numa mesma linha de comando, o que dá erro. Acho que precisaria separar esses dois `cd`
![image](https://github.com/PHPSP/phpsp.org.br/assets/3905582/1516d865-0f2e-4926-9bb7-94b1c9d2ee1a)

Aqui acho que `clear` e `CTRL + L` deveria ser separado também
![image](https://github.com/PHPSP/phpsp.org.br/assets/3905582/90ac7bc6-81d8-417a-ad25-8538eca59835)

Aqui `elissandra@elissandra-Lenovo-IdeaPad-S400:~$ ` não faz parte do comando, acho que dá pra jogar fora
![image](https://github.com/PHPSP/phpsp.org.br/assets/3905582/3f44b236-1146-48d4-bac1-251498e4970d)

2024-01-11 10:37 UTC, nawarian approved these changes

2024-01-11 10:38 UTC, merged